# -*- coding: utf-8 -*-
"""solution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVbrzQkLb7fI_vzshMtBFl5YAONW1if_
"""

def decrypt(text):
  text = text.split('\n')
  numbers = []
  for i in range(0, len(text)):
    first_digit = ""
    last_digit = ""
    for char in text[i]:
      if char.isdigit():
        first_digit = char
        break

    for char in reversed(text[i]):
      if char.isdigit():
        last_digit = char
        break
    numbers.append(int(first_digit + last_digit))
  return sum(numbers)